# -*- coding: utf-8 -*-
"""Lab1_terver.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vX7vITlYgTwfM9daRr-yaduqWfI3Z18w
"""

import xlrd
from collections import Counter

book_1 = xlrd.open_workbook('/content/sample_data/01_Образование_организации_01.xlsx')
book_2 = xlrd.open_workbook('/content/sample_data/01_Образование_организации_02.xlsx')

sheet_1 = book_1.sheet_by_name('Отчет')
sheet_2 = book_2.sheet_by_name('Отчет')

region_dict = {}

for i in range(sheet_1.nrows-4):
  if (sheet_1.cell(i+4,0).value.find('федеральный округ') == -1):
    region_dict[sheet_1.cell(i+4,0).value] = [0, float(sheet_1.cell(i+4,1).value), float(sheet_1.cell(i+4,2).value), 0]

print(len(region_dict))

for i in range(sheet_2.nrows-4):
    if(region_dict.get(sheet_2.cell(i+4,0).value)!= None):
      tmp = region_dict[sheet_2.cell(i+4,0).value]
      try:
        tmp[0] = float(sheet_2.cell(i+4,1).value)
      except:
        tmp[0] = 0.0
      try:
        tmp[3] = float(sheet_2.cell(i+4,2).value)
      except:
        tmp[3] = 0.0
      region_dict[sheet_2.cell(i+4,0).value] = tmp
print(len(region_dict))

for name, value in region_dict.items():
  max_value = max(value, key=lambda x:float(x))
  max_year = 2015 + value.index(max_value)
  avg = sum(value)/4
  value.insert(4, avg)
  value.insert(5, max_year)
print(region_dict)

years = []
for name, value in region_dict.items():
  years.append(value[5])
year_counter = Counter(years)
print(year_counter)

sorted_dict = dict(sorted(region_dict.items(), key= lambda item: item[1][4]))
print(sorted_dict)